import { PolicyPage } from "@/components/content/policy-page";

const intro = [
  "This User License Agreement (“ULA”) governs the limited right granted to you to access and use the Platform and related software, files, updates, and services made available by xrs s. r. o.",
  "This Agreement applies together with the Terms of Use and does not replace them.",
];

const sections = [
  { title: "1. Limited License", blocks: [{ type: "paragraph", content: "Subject to your compliance with the Terms of Use, this ULA, and all applicable rules, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable right to access and use the Platform and any related materials made available to your account during an active access period." }, { type: "paragraph", content: "This right is granted solely for your own use." }, { type: "paragraph", content: "No purchase, payment, or redemption transfers ownership of the Platform, software, code, files, or related intellectual property." }] },
  { title: "2. Account and Device Binding", blocks: [{ type: "paragraph", content: "The license or access right granted under this ULA may be tied to:" }, { type: "list", items: ["your account,", "your account state,", "device state,", "hardware or device identification controls,", "security and anti-abuse systems."] }, { type: "paragraph", content: "Device changes, device resets, and account reviews may require support review, manual verification, or approval." }, { type: "paragraph", content: "You may not attempt to bypass or interfere with any device or security controls." }] },
  { title: "3. No Transfer", blocks: [{ type: "paragraph", content: "You may not:" }, { type: "list", items: ["transfer your account,", "transfer licensed access,", "lend or share access,", "sell access,", "sublicense access,", "allow another person to use access granted to your account."] }, { type: "paragraph", content: "Any attempted transfer is void." }] },
  { title: "4. Prohibited Conduct", blocks: [{ type: "paragraph", content: "You may not, except where non-waivable law expressly permits it:" }, { type: "list", items: ["copy, reproduce, distribute, or republish protected parts of the Platform,", "reverse engineer, decompile, disassemble, analyze, or attempt to derive source code or protected logic,", "bypass technical protection, entitlement, or device checks,", "modify or tamper with protected delivery methods,", "attempt unauthorized extraction of files, updates, or protected content,", "use the Platform in any way that violates applicable law or our rules."] }] },
  { title: "5. Updates and Changes", blocks: [{ type: "paragraph", content: "We may update, modify, suspend, restrict, replace, or discontinue any part of the Platform, including files, functionality, access methods, delivery methods, and supported environments, at any time." }, { type: "paragraph", content: "You acknowledge that updates may:" }, { type: "list", items: ["change features,", "alter compatibility,", "restrict earlier methods,", "replace prior files,", "require revalidation of access."] }, { type: "paragraph", content: "We are not obliged to maintain any specific version or file indefinitely." }] },
  { title: "6. Revocation", blocks: [{ type: "paragraph", content: "The limited right granted under this ULA may be revoked or restricted where:" }, { type: "list", items: ["your subscription expires,", "your account is suspended or terminated,", "a key is revoked,", "a payment is disputed or reversed,", "abuse or fraud is detected,", "device or security controls are violated,", "the Terms of Use or Behavior Rules are violated."] }] },
  { title: "7. Intellectual Property", blocks: [{ type: "paragraph", content: "All rights, title, and interest in the Platform, branding, design, code, files, updates, content, and related materials remain with us or our licensors." }, { type: "paragraph", content: "No rights are granted except those expressly stated in this ULA." }] },
  { title: "8. No Warranty", blocks: [{ type: "paragraph", content: "The Platform and all related materials are provided on an “as is” and “as available” basis to the maximum extent permitted by law." }, { type: "paragraph", content: "We do not warrant:" }, { type: "list", items: ["uninterrupted availability,", "error-free operation,", "compatibility,", "merchantability,", "fitness for a particular purpose,", "that the Platform will meet your expectations."] }] },
  { title: "9. Limitation of Liability", blocks: [{ type: "paragraph", content: "To the maximum extent permitted by law, we are not liable for any indirect, incidental, consequential, or special damages arising from your access to or use of the Platform, including loss of access, files, account state, data, or service continuity." }, { type: "paragraph", content: "Nothing in this Agreement limits liability that cannot legally be limited." }] },
  { title: "10. Governing Law", blocks: [{ type: "paragraph", content: "This ULA is governed by the laws of the Slovak Republic, subject to mandatory consumer protections that may apply to you under applicable law." }] },
] as const;

export default function LegalPage() {
  return <PolicyPage effectiveDate="April 7, 2026" intro={intro} sections={sections} title="User License Agreement" />;
}
