const actionLabels: Record<string, string> = {
  "banner.created": "Banner created",
  "banner.updated": "Banner updated",
  "banner.published": "Banner published",
  "banner.unpublished": "Banner unpublished",
  "homepageBlock.created": "Homepage block created",
  "homepageBlock.updated": "Homepage block updated",
  "homepageBlock.published": "Homepage block published",
  "homepageBlock.unpublished": "Homepage block unpublished",
  "homepageBlock.reordered": "Homepage blocks reordered",
  "badge.created": "Badge created",
  "badge.updated": "Badge updated",
  "badge.published": "Badge published",
  "badge.unpublished": "Badge unpublished",
  "badge.assigned": "Badge assigned",
  "badge.removed": "Badge removed",
  "reseller.created": "Reseller created",
  "reseller.updated": "Reseller updated",
  "reseller.batch.created": "Reseller batch created",
  "reseller.keys.generated": "Reseller keys generated",
  "reseller.keys.issued": "Reseller batch issued",
  "reseller.key.revoked": "Reseller key revoked",
  "reseller.key.redeemed": "Reseller key redeemed",
  "announcement.created": "Announcement created",
  "announcement.updated": "Announcement updated",
  "announcement.published": "Announcement published",
  "announcement.unpublished": "Announcement unpublished",
  "changelog.created": "Changelog created",
  "changelog.updated": "Changelog updated",
  "changelog.published": "Changelog published",
  "changelog.unpublished": "Changelog unpublished",
  "forum.categoryCreated": "Forum category created",
  "forum.categoryUpdated": "Forum category updated",
  "forum.categoriesReordered": "Forum categories reordered",
  "forum.threadModerated": "Thread moderated",
  "forum.postModerated": "Post moderated",
  "ticket.assigned": "Ticket assigned",
  "ticket.statusUpdated": "Ticket status updated",
  "ticket.replyAdded": "Ticket reply added",
  "ticket.internalNoteAdded": "Ticket internal note added",
  "ticket.created": "Ticket created",
  "ticket.closed": "Ticket closed",
  "ticket.reopened": "Ticket reopened",
  "user.setAccountState": "User account state changed",
};

export function getAdminActionLabel(action: string) {
  return actionLabels[action] ?? action;
}
