import { PolicyPage } from "@/components/content/policy-page";

const intro = [
  "This Privacy Policy explains how xrs s. r. o. collects, uses, stores, and shares personal data in connection with the marcelkaware Platform.",
];

const sections = [
  { title: "1. Controller", blocks: [{ type: "paragraph", content: "The controller of your personal data is:" }, { type: "list", items: ["xrs s. r. o.", "ICO: 23612819", "Registered address: Viktora Bilčíka 2911/10, 915 01 Nové Mesto nad Váhom, Slovakia", "Contact: legal@marcelkaware.dev"] }] },
  { title: "2. What Data We Collect", blocks: [{ type: "paragraph", content: "Depending on how you use the Platform, we may collect:" }, { type: "paragraph", content: "Account data" }, { type: "list", items: ["email address", "username", "password or authentication-related metadata", "account status and account history"] }, { type: "paragraph", content: "Payment and access data" }, { type: "list", items: ["payment status", "subscription status", "transaction references", "reseller key redemption data", "invoice or billing metadata", "dispute, refund, or chargeback-related data"] }, { type: "paragraph", content: "Device and security data" }, { type: "list", items: ["IP address", "device-related identifiers", "hardware or device control data", "HWID-related records", "security logs", "fraud-prevention and anti-abuse indicators"] }, { type: "paragraph", content: "Support and community data" }, { type: "list", items: ["support ticket contents", "support replies", "forum posts", "messages or reports submitted through moderation or appeal tools", "content moderation history"] }, { type: "paragraph", content: "Technical and usage data" }, { type: "list", items: ["session data", "cookies or similar identifiers", "page interactions", "diagnostics", "error and event logs"] }] },
  { title: "3. Why We Use Personal Data", blocks: [{ type: "paragraph", content: "We use personal data to:" }, { type: "list", items: ["create and manage accounts,", "authenticate users,", "deliver paid or redeemed access,", "process payments and confirm payment state,", "operate support and community features,", "enforce our Terms and security rules,", "detect fraud, abuse, or unauthorized access,", "review disputes, chargebacks, resets, and appeals,", "maintain and improve the Platform,", "comply with legal, tax, accounting, and security obligations."] }] },
  { title: "4. Legal Bases", blocks: [{ type: "paragraph", content: "Where GDPR or similar laws apply, we rely on one or more of the following legal bases:" }, { type: "list", items: ["performance of a contract,", "compliance with legal obligations,", "our legitimate interests in operating, securing, and improving the Platform,", "your consent, where consent is required,", "establishment, exercise, or defense of legal claims, where applicable."] }] },
  { title: "5. Payments", blocks: [{ type: "paragraph", content: "We may process card payments through Stripe." }, { type: "paragraph", content: "We may process crypto-related payment flows through a self-hosted BTCPay Server environment operated by us." }, { type: "paragraph", content: "Payment initiation does not itself create entitlement. We may use payment records, invoice state, webhook data, dispute records, and redemption data to determine access status and enforce billing rules." }] },
  { title: "6. Service Providers and Recipients", blocks: [{ type: "paragraph", content: "We may share relevant data with service providers and recipients that support operation of the Platform, such as:" }, { type: "list", items: ["Convex for backend infrastructure and data services", "Stripe for payment processing", "self-hosted BTCPay Server infrastructure operated by us for crypto payment handling", "Resend for email delivery", "PostHog Cloud EU for analytics, if enabled", "Sentry for error monitoring and diagnostics, if enabled", "hosting, DNS, security, and operational providers where required for Platform operation"] }, { type: "paragraph", content: "We may also disclose data:" }, { type: "list", items: ["where required by law,", "to respond to legal process,", "to protect rights, safety, or security,", "in connection with fraud prevention, dispute handling, or legal claims."] }] },
  { title: "7. Cookies and Similar Technologies", blocks: [{ type: "paragraph", content: "We may use cookies and similar technologies for:" }, { type: "list", items: ["authentication,", "session management,", "security,", "Platform functionality,", "analytics and performance measurement."] }, { type: "paragraph", content: "Some cookies may be strictly necessary for operation of the Platform. Others may be used for analytics or service improvement where implemented." }] },
  { title: "8. Retention", blocks: [{ type: "paragraph", content: "We retain data for as long as needed for the purposes described in this Policy, including:" }, { type: "list", items: ["account data: while your account remains active and for a reasonable period afterward where needed for security, legal compliance, or claims", "payment and accounting records: for as long as required by applicable tax, accounting, or legal obligations", "support tickets and forum content: until deleted, removed, or no longer needed, subject to legal, security, moderation, or claims-related retention needs", "audit and security logs: for as long as reasonably necessary for fraud prevention, abuse detection, enforcement, security, and legal claims"] }, { type: "paragraph", content: "We may retain certain data longer where required or justified by law, fraud prevention, dispute handling, or legal defense." }] },
  { title: "9. International Transfers", blocks: [{ type: "paragraph", content: "Because the Platform is offered globally, some service providers or infrastructure may process data outside your country of residence." }, { type: "paragraph", content: "Where required by law, we take appropriate steps to protect personal data transferred internationally." }] },
  { title: "10. Your Rights", blocks: [{ type: "paragraph", content: "Where applicable law grants you rights, you may have the right to:" }, { type: "list", items: ["access your personal data,", "correct inaccurate data,", "request deletion,", "request restriction of processing,", "object to certain processing,", "request data portability,", "withdraw consent where processing is based on consent,", "lodge a complaint with a competent supervisory authority."] }, { type: "paragraph", content: "These rights may be limited where legal exemptions apply or where retention is necessary for legal, security, or fraud-prevention reasons." }] },
  { title: "11. Security", blocks: [{ type: "paragraph", content: "We use reasonable technical and organizational measures intended to protect personal data, account integrity, and operational security." }, { type: "paragraph", content: "No system can be guaranteed fully secure, and we cannot guarantee absolute security." }] },
  { title: "12. Community and Public Content", blocks: [{ type: "paragraph", content: "Information you choose to publish in community areas may be visible to other users depending on your profile, permissions, and content visibility settings." }, { type: "paragraph", content: "We may moderate or remove content in accordance with our rules and operational needs." }] },
  { title: "13. Children", blocks: [{ type: "paragraph", content: "The Platform is not directed specifically to children." }, { type: "paragraph", content: "If you are legally required to have parental or guardian authorization in order to use the Platform, you must obtain it before use." }] },
  { title: "14. Contact", blocks: [{ type: "paragraph", content: "For privacy-related questions or requests, contact: legal@marcelkaware.dev" }] },
] as const;

export default function PrivacyPage() {
  return <PolicyPage effectiveDate="April 7, 2026" intro={intro} sections={sections} title="Privacy Policy" />;
}
