import { PolicyPage } from "@/components/content/policy-page";

const intro = [
  "These Terms of Use govern access to and use of the marcelkaware platform operated by xrs s. r. o., ICO 23612819, with its registered address at Viktora Bilčíka 2911/10, 915 01 Nové Mesto nad Váhom, Slovakia (“we”, “us”, “our”).",
  "These Terms apply to your use of the website, account system, downloads, subscription access, support, forum and community features, updates, reseller key redemption, and related services available through https://marcelkaware.dev (the “Platform”).",
  "By creating an account, purchasing access, redeeming a key, or using any part of the Platform, you agree to these Terms.",
  "If you do not agree, do not use the Platform.",
];

const sections = [
  { title: "1. Eligibility", blocks: [{ type: "paragraph", content: "You represent that:" }, { type: "list", items: ["you have the legal capacity to enter into these Terms in your country of residence; or", "if you are below the age of legal majority, you are using the Platform with the consent and authorization of a parent or legal guardian where required by applicable law."] }, { type: "paragraph", content: "You may not use the Platform if your use would violate applicable law." }] },
  { title: "2. Operator Details", blocks: [{ type: "list", items: ["Operator: xrs s. r. o.", "ICO: 23612819", "Registered address: Viktora Bilčíka 2911/10, 915 01 Nové Mesto nad Váhom, Slovakia", "Legal contact: legal@marcelkaware.dev"] }] },
  { title: "3. Account Ownership", blocks: [{ type: "paragraph", content: "Each account is issued for one person only." }, { type: "paragraph", content: "You may not:" }, { type: "list", items: ["share your account,", "lend your account,", "sell your account,", "transfer your account,", "allow another person to use your account,", "give another person access to your credentials or session."] }, { type: "paragraph", content: "You are responsible for maintaining the confidentiality of your login credentials and for all activity occurring through your account." }, { type: "paragraph", content: "We may rely on account activity, session data, device controls, security logs, payment state, redemption history, and related records when reviewing account ownership, misuse, or abuse." }] },
  { title: "4. Access Model", blocks: [{ type: "paragraph", content: "The Platform operates on a subscription-based access model." }, { type: "paragraph", content: "Paid access may be granted through:" }, { type: "list", items: ["direct purchase through approved payment methods,", "approved reseller key redemption,", "any other access method expressly authorized by us."] }, { type: "paragraph", content: "Paid access is tied to the account that completed the purchase or redeemed the approved key." }, { type: "paragraph", content: "Access may also be tied to:" }, { type: "list", items: ["device state,", "account state,", "hardware or device identification controls,", "security and anti-abuse systems,", "review and verification workflows."] }, { type: "paragraph", content: "Paid access is not ownership of the Platform or any related software, files, updates, or services." }] },
  { title: "5. Payment Confirmation and Fulfillment", blocks: [{ type: "paragraph", content: "Access is granted only after successful confirmation of payment or successful redemption of an approved key." }, { type: "paragraph", content: "We may use:" }, { type: "list", items: ["Stripe for card payments,", "self-hosted BTCPay Server infrastructure for crypto payments,", "approved reseller workflows for key-based access."] }, { type: "paragraph", content: "Payment or invoice initiation alone does not create entitlement. Access is only granted after confirmed successful processing according to the relevant payment or redemption flow." }, { type: "paragraph", content: "For crypto payments, underpayment, stale invoices, incorrect transfers, abandoned invoices, unpaid invoices, or delayed confirmations do not create a right to access unless and until we confirm the relevant payment state." }] },
  { title: "6. Subscription Expiry", blocks: [{ type: "paragraph", content: "When an active subscription or paid access period ends:" }, { type: "list", items: ["paid-only downloads may be removed,", "paid-only forum or community areas may become unavailable,", "launcher or device-linked access may stop working,", "paid support eligibility may be limited or removed,", "the account itself may remain active unless separately restricted or terminated."] }, { type: "paragraph", content: "Public or unrestricted parts of the Platform may remain available if the account still exists and is not restricted." }] },
  { title: "7. Billing, Refunds, and Chargebacks", blocks: [{ type: "paragraph", content: "Unless required by applicable law or expressly approved by us, payments are final." }, { type: "paragraph", content: "We may, at our sole discretion, approve a refund where:" }, { type: "list", items: ["the issue is on our side,", "a technical or account problem clearly prevented delivery of the purchased access,", "a refund is otherwise required by law."] }, { type: "paragraph", content: "You may not abuse payment flows, refund requests, disputes, or chargeback systems." }, { type: "paragraph", content: "Any chargeback, payment dispute, fraudulent payment activity, or abuse of the payment process may result in immediate suspension or termination of the related account and access, without prejudice to any other rights or remedies available to us." }, { type: "paragraph", content: "Where required by applicable law, mandatory consumer rights remain unaffected." }] },
  { title: "8. Right of Withdrawal for Consumers", blocks: [{ type: "paragraph", content: "If you are a consumer in a jurisdiction that grants a statutory withdrawal right for digital content or digital services, that right may be limited or lost once performance begins, where permitted by applicable law, including where you:" }, { type: "list", items: ["expressly request or consent to immediate performance before the withdrawal period ends, and", "acknowledge that you may lose your withdrawal right once performance begins."] }, { type: "paragraph", content: "Where applicable law grants you rights that cannot be waived or excluded, those rights remain in force." }] },
  { title: "9. Keys and Redemptions", blocks: [{ type: "paragraph", content: "Keys may be issued through approved internal or reseller channels." }, { type: "paragraph", content: "A key may be redeemed by the person who uses it on the target account, unless the specific key or campaign states otherwise." }, { type: "paragraph", content: "You may not:" }, { type: "list", items: ["duplicate keys,", "reuse redeemed keys,", "resell or distribute keys without authorization,", "redeem revoked or unauthorized keys,", "attempt to manipulate the redemption flow,", "obtain access outside the intended account and redemption process."] }, { type: "paragraph", content: "We may revoke, suspend, invalidate, or refuse any key or redeemed access where we reasonably suspect fraud, abuse, duplication, unauthorized distribution, chargeback-related abuse, or other misuse." }] },
  { title: "10. Restrictions", blocks: [{ type: "paragraph", content: "You may not:" }, { type: "list", items: ["share or transfer account access,", "bypass entitlement, payment, security, or device checks,", "interfere with the Platform or other users,", "abuse support or moderation systems,", "attempt to gain access outside the intended purchase or redemption flow,", "scrape, attack, overload, or disrupt the Platform,", "upload, post, or transmit spam, fraud, harassment, illegal content, impersonation, or abusive material,", "engage in any conduct that may harm the Platform, its infrastructure, its operators, or other users."] }] },
  { title: "11. Support and Appeals", blocks: [{ type: "paragraph", content: "Normal support is available through the intended support flow for eligible accounts." }, { type: "paragraph", content: "Restricted or banned accounts may lose normal support access and may be limited to the dedicated appeal or contact path only." }, { type: "paragraph", content: "Support requests, account reviews, payment issues, access checks, and device reset requests may require additional verification before any action is taken." }, { type: "paragraph", content: "We may deny, close, or refuse requests that are abusive, incomplete, fraudulent, duplicative, or inconsistent with Platform security." }] },
  { title: "12. Moderation and Community Access", blocks: [{ type: "paragraph", content: "Use of community areas is also subject to our Behavior Rules." }, { type: "paragraph", content: "We may:" }, { type: "list", items: ["remove content,", "hide content,", "lock threads,", "restrict posting,", "restrict messaging,", "suspend community access,", "suspend or terminate accounts,", "reject appeals where justified by the evidence available to us."] }, { type: "paragraph", content: "We are not required to keep any specific content, thread, post, or forum area available permanently." }] },
  { title: "13. Changes to the Platform", blocks: [{ type: "paragraph", content: "We may change, suspend, replace, or discontinue any part of the Platform at any time, including:" }, { type: "list", items: ["features,", "prices,", "access methods,", "community areas,", "launcher support,", "billing methods,", "key systems,", "support processes,", "device controls,", "availability of files or updates."] }, { type: "paragraph", content: "We do not guarantee uninterrupted availability or permanent access to any specific feature or file." }] },
  { title: "14. Termination and Suspension", blocks: [{ type: "paragraph", content: "We may restrict, suspend, or permanently terminate any account where we reasonably believe that:" }, { type: "list", items: ["these Terms were violated,", "a payment flow was abused,", "Platform security was threatened,", "keys were misused,", "community or support systems were abused,", "the account was used fraudulently,", "continued access would create operational, legal, or security risk."] }, { type: "paragraph", content: "Suspension or termination may include removal of:" }, { type: "list", items: ["paid access,", "community access,", "support access,", "redemption rights,", "download access,", "device-linked access."] }] },
  { title: "15. Disclaimer", blocks: [{ type: "paragraph", content: "The Platform is provided on an “as is” and “as available” basis to the maximum extent permitted by applicable law." }, { type: "paragraph", content: "We do not guarantee:" }, { type: "list", items: ["uninterrupted service,", "permanent availability,", "error-free operation,", "compatibility with every environment or device,", "permanent access to any feature, file, update, or support path."] }] },
  { title: "16. Limitation of Liability", blocks: [{ type: "paragraph", content: "To the maximum extent permitted by applicable law, we are not liable for any indirect, incidental, consequential, special, exemplary, or punitive damages, or for any loss of profits, revenue, data, account state, goodwill, business opportunity, or access arising from or related to:" }, { type: "list", items: ["use of or inability to use the Platform,", "payment issues,", "service interruptions,", "account restrictions,", "content moderation,", "device restrictions,", "unauthorized use of your account,", "third-party provider failures,", "enforcement of these Terms."] }, { type: "paragraph", content: "Nothing in these Terms excludes liability that cannot be excluded under applicable law." }] },
  { title: "17. Governing Law and Venue", blocks: [{ type: "paragraph", content: "These Terms are governed by the laws of the Slovak Republic, except where mandatory consumer protection law requires otherwise." }, { type: "paragraph", content: "If you are a consumer residing in the European Union, nothing in these Terms deprives you of mandatory protections granted by the law of your country of residence." }, { type: "paragraph", content: "Any disputes shall be submitted to the competent courts of the Slovak Republic, unless mandatory law provides otherwise." }] },
  { title: "18. Changes to These Terms", blocks: [{ type: "paragraph", content: "We may revise these Terms from time to time." }, { type: "paragraph", content: "The latest version will be made available on the Platform with an updated effective date." }, { type: "paragraph", content: "Your continued use of the Platform after updated Terms take effect constitutes acceptance of the revised Terms." }] },
  { title: "19. Contact", blocks: [{ type: "paragraph", content: "Legal and support contact: legal@marcelkaware.dev" }] },
] as const;

export default function TosPage() {
  return <PolicyPage effectiveDate="April 7, 2026" intro={intro} sections={sections} title="Terms of Use" />;
}
