import { PolicyPage } from "@/components/content/policy-page";

const intro = [
  "These Behavior Rules govern conduct across community areas, tickets, support channels, reports, appeals, and other user-facing parts of the Platform.",
  "By using these areas, you agree to follow these rules.",
];

const sections = [
  { title: "1. Core Standard", blocks: [{ type: "paragraph", content: "You must use the Platform in a respectful, lawful, and non-abusive manner." }, { type: "paragraph", content: "The Platform is provided for legitimate use within the intended account, support, and community flow." }] },
  { title: "2. Prohibited Conduct", blocks: [{ type: "paragraph", content: "You may not:" }, { type: "list", items: ["harass, threaten, or abuse other users or staff,", "spam, flood, or post repetitive content,", "impersonate another person or entity,", "use fraudulent or deceptive conduct,", "post unlawful, infringing, hateful, or violent content,", "post doxxing, blackmail, extortion, or malicious personal disclosures,", "advertise or solicit unauthorized services,", "trade, sell, or promote unauthorized account sharing,", "distribute or promote stolen or unauthorized keys,", "abuse the report or appeal system,", "submit false support claims,", "evade prior moderation or account restrictions."] }] },
  { title: "3. Community Content", blocks: [{ type: "paragraph", content: "You remain responsible for content you post." }, { type: "paragraph", content: "You may not post content that:" }, { type: "list", items: ["violates law,", "violates the rights of others,", "contains fraud or scams,", "is abusive, obscene, or malicious,", "is intended to disrupt the Platform,", "promotes unauthorized transfer or abuse of access."] }, { type: "paragraph", content: "We may remove, hide, edit formatting of, lock, limit visibility of, or otherwise moderate content at our discretion where needed for safety, compliance, enforcement, or operational reasons." }] },
  { title: "4. Support Conduct", blocks: [{ type: "paragraph", content: "Support must not be abused." }, { type: "paragraph", content: "You may not:" }, { type: "list", items: ["repeatedly open duplicate tickets,", "submit knowingly false claims,", "threaten staff,", "abuse reset or recovery requests,", "misuse the appeal system,", "pressure staff to bypass policy."] }, { type: "paragraph", content: "We may close, merge, deny, or restrict support requests where abuse, duplication, or bad-faith use is detected." }] },
  { title: "5. Reports and Appeals", blocks: [{ type: "paragraph", content: "We may provide:" }, { type: "list", items: ["onsite reporting tools,", "onsite moderation appeals,", "email-based contact or appeal channels."] }, { type: "paragraph", content: "Submitting a report or appeal does not guarantee reversal of a moderation or account decision." }, { type: "paragraph", content: "We may request additional information before reviewing a report or appeal." }] },
  { title: "6. Moderation Actions", blocks: [{ type: "paragraph", content: "We may take moderation action including:" }, { type: "list", items: ["warnings,", "content removal,", "content hiding,", "thread locks,", "posting restrictions,", "support restrictions,", "suspension,", "permanent termination,", "restriction of community or account access."] }, { type: "paragraph", content: "We are not obliged to provide a warning before action is taken where immediate action is justified." }] },
  { title: "7. Account and Community Evasion", blocks: [{ type: "paragraph", content: "You may not attempt to evade moderation, restrictions, or suspension by:" }, { type: "list", items: ["creating replacement accounts,", "using other accounts,", "using another person’s account,", "re-entering restricted community areas through unauthorized means."] }] },
  { title: "8. Staff and Operator Discretion", blocks: [{ type: "paragraph", content: "We may interpret and enforce these Rules in good faith to protect the Platform, users, staff, and operations." }, { type: "paragraph", content: "Not every form of harmful or abusive conduct can be listed in advance. Conduct substantially similar in effect may also be restricted." }] },
  { title: "9. Relation to Other Documents", blocks: [{ type: "paragraph", content: "These Behavior Rules form part of the broader Platform rules together with:" }, { type: "list", items: ["Terms of Use,", "User License Agreement,", "Privacy Policy,", "Help / Billing / Refund / Appeals."] }] },
] as const;

export default function BehaviorPage() {
  return <PolicyPage effectiveDate="April 7, 2026" intro={intro} sections={sections} title="Behavior Rules" />;
}
